steps:
# Step 1: Checkout the code from GitHub 
 - name: 'gcr.io/cloud-builders/git' 
   args: ['clone','https://github.com/dom-j/gcp-resume-challenge.git','resume-frontend',]
   env:
    - 'CLOUDSDK_COMPUTE_REGION=europe-west1'
  
#Deploy to Cloud Storage

 - name: 'gcr.io/cloud-builders/gsutil'
   args: ['cp', '-r','resume-frontend/resume','gs://website-by-dom-j',]
   env:
    - 'CLOUDSDK_COMPUTE_REGION=europe-west1'

# Invalidate Cloud CDN cache and redeploy

 - name: 'gcr.io/cloud-builders/gcloud'
   args: ['cdn','invalidation','create','--path','/*','--description','Cache invalidation on redeploy']